## Kilometers to Miles conversion calculator

In [1]:
dist_in_km = [3, 5, 10, 21.1, 42.195]

dist_in_mile = []

for d in dist_in_km:
    dist_in_mile.append(d * 0.62137)

print(dist_in_mile)

[1.86411, 3.1068499999999997, 6.213699999999999, 13.110907000000001, 26.21870715]


## Kilometers to Miles conversion calculator

#### List Comprehension

In [2]:
dist_in_km = [3, 5, 10, 21.1, 42.195]

dist_in_mile = [d * 0.62137 for d in dist_in_km]

print(dist_in_mile)

[1.86411, 3.1068499999999997, 6.213699999999999, 13.110907000000001, 26.21870715]


## Kilometers to Miles conversion calculator

#### Lambda Expression & map() 

In [3]:
dist_in_km = [3, 5, 10, 21.1, 42.195]

dist_in_mile = list(map(lambda d : d * 0.62137, dist_in_km))

print(dist_in_mile)

[1.86411, 3.1068499999999997, 6.213699999999999, 13.110907000000001, 26.21870715]


## Kilometers to Miles conversion calculator

#### Numerical Python  

* $np.array():$ convert $list$ to $ndarray$

In [4]:
import numpy as np

dist_in_km = [3, 5, 10, 21.1, 42.195]
dist_in_km = np.array(dist_in_km)

dist_in_mile = dist_in_km * 0.62137

print(dist_in_mile)

[ 1.86411     3.10685     6.2137     13.110907   26.21870715]


In [5]:
dist_in_km = [3, 5, 10, 21.1, 42.195]
print(type(dist_in_km))
dist_in_km = np.array(dist_in_km)
print(type(dist_in_km))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
import numpy as np

print(np.arange(8))
print(np.arange(1, 8)) 
print(np.arange(1, 10, 2))

[0 1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[1 3 5 7 9]


In [7]:
arr = np.linspace(1, 12, 10)
print(arr)
print(arr.dtype)
arr = arr.astype(int)
print(arr)
print(arr.dtype)

[ 1.          2.22222222  3.44444444  4.66666667  5.88888889  7.11111111
  8.33333333  9.55555556 10.77777778 12.        ]
float64
[ 1  2  3  4  5  7  8  9 10 12]
int64


In [8]:
lst = [42.195, 'km', True] 

for i in lst:
    print(type(i))

arr = np.array(lst)
for i in arr:
    print(type(i))
    
for i in lst:
    print(i)

for i in arr:
    print(i)

<class 'float'>
<class 'str'>
<class 'bool'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
42.195
km
True
42.195
km
True


In [9]:
u = np.array([8, 7]).reshape(2, 1)
v = np.array([8, 7, 6]).reshape(3, 1)
print(u)
print("\n")
print(v)

[[8]
 [7]]


[[8]
 [7]
 [6]]


In [10]:
g = np.arange(24)
print(g)
print("Rank:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Rank: 1


In [11]:
g.shape = (2, 3, 4)
print(g)
print("Rank:", g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Rank: 3


In [12]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
print("mean =", a.mean())

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]
mean = 6.766666666666667


In [13]:
for func in (a.min, a.max, a.sum, a.prod, a.std, a.var):
    print(func.__name__, "=", func())

min = -2.5
max = 12.0
sum = 40.6
prod = -71610.0
std = 5.084835843520964
var = 25.855555555555554
