# Sample Code

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.python import keras
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, Flatten, Conv2D, Dropout

a=pd.read_csv("/home/cesare/Downloads/digit-recognizer/train.csv")
a.shape

/home/cesare/anaconda3/envs/py35/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


(42000, 785)

In [2]:
a.head(3)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  

[3 rows x 785 columns]

In [3]:
a.drop('label', axis=1).head(3)

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  

[3 rows x 784 columns]

In [4]:
img_rows, img_cols = 28, 28
num_classes = 10

In [7]:
def data_prep(raw):
    out_y = keras.utils.to_categorical(raw.label, num_classes)

    num_images = raw.shape[0]
    x_as_array = raw.values[:,1:]
    x_shaped_array = x_as_array.reshape(num_images, img_rows, img_cols, 1)
    out_x = x_shaped_array / 255
    return out_x, out_y

train_size = 30000
train_file = "/home/cesare/Downloads/digit-recognizer/train.csv"
raw_data = pd.read_csv(train_file)

In [8]:
print("Shape of raw_data:", raw_data.shape)

Shape of raw_data: (42000, 785)


In [9]:
print("Y label: \n", raw_data.label.head(7))
print("\n")
print("Shape of Y:", raw_data.label.shape)

Y label: 
 0    1
1    0
2    1
3    4
4    0
5    0
6    7
Name: label, dtype: int64


Shape of Y: (42000,)


In [10]:
Out_Y = keras.utils.to_categorical(raw_data.label, num_classes)
print("Y label: \n", Out_Y)
print("\n")
print("Shape of Y:", Out_Y.shape)

Y label: 
 [[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


Shape of Y: (42000, 10)


In [11]:
number_images = raw_data.shape[0]
print("Number of images              :", number_images)
print("\n")

X_As_Array = raw_data.values[:,1:]
print("X array:\n", X_As_Array)
print("Shape of X array              :", X_As_Array.shape)
print("\n")

X_Shaped_Array = X_As_Array.reshape(number_images, img_rows, img_cols, 1)
print("Shape of shaped X array       :", X_Shaped_Array.shape)
print("\n")

X_Shaped_Array_Back = X_Shaped_Array.reshape(42000, -1)
#X_Shaped_Array_Back = X_Shaped_Array.reshape(42000, 2, -1)
#X_Shaped_Array_Back = X_Shaped_Array.reshape(42000, 2, 2, -1)
print("Shape of shaped X array (Back):", X_Shaped_Array_Back.shape)

Number of images              : 42000


X array:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Shape of X array              : (42000, 784)


Shape of shaped X array       : (42000, 28, 28, 1)


Shape of shaped X array (Back): (42000, 784)


## reshape

In [12]:
c = np.arange(24).reshape(3,2,4)
print(c)
print("\n")
print("Shape of c          :", c.shape)
print("Shape of c (reshape):", c.reshape(3, -1).shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


Shape of c          : (3, 2, 4)
Shape of c (reshape): (3, 8)


In [13]:
a = np.arange(48).reshape(3,2,2,4)
print(a)
print("\n")
print("Shape of a          :", a.shape)
print("Shape of a (reshape):", a.reshape(3, -1).shape)

[[[[ 0  1  2  3]
   [ 4  5  6  7]]

  [[ 8  9 10 11]
   [12 13 14 15]]]


 [[[16 17 18 19]
   [20 21 22 23]]

  [[24 25 26 27]
   [28 29 30 31]]]


 [[[32 33 34 35]
   [36 37 38 39]]

  [[40 41 42 43]
   [44 45 46 47]]]]


Shape of a          : (3, 2, 2, 4)
Shape of a (reshape): (3, 16)


## reshape

In [14]:
x, y = data_prep(raw_data)

In [15]:
print(x.shape)
print(y.shape)

(42000, 28, 28, 1)
(42000, 10)


In [16]:
# 30 feature maps with a size of 3×3
# Fully connected layer with 128 units and a RELU activation function
# Fully connected output layer with 10 units and a softmax activation function

model = Sequential()
model.add(Conv2D(30, kernel_size=(3, 3),
                 strides=2,
                 activation='relu',
                 input_shape=(img_rows, img_cols, 1)))
Dropout(0.5)
model.add(Conv2D(30, kernel_size=(3, 3), strides=2, activation='relu'))
Dropout(0.5)
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer='adam',
              metrics=['accuracy'])
model.fit(x, y,
          batch_size=128,
          epochs=2,
          validation_split = 0.2)

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Train on 33600 samples, validate on 8400 samples
Epoch 1/2
33600/33600 [==============================]33600/33600 [==============================] - 7s 218us/step - loss: 0.4347 - acc: 0.8743 - val_loss: 0.1616 - val_acc: 0.9529

Epoch 2/2
33600/33600 [==============================]33600/33600 [==============================] - 7s 220us/step - loss: 0.1253 - acc: 0.9636 - val_loss: 0.0909 - val_acc: 0.9710

